monolog:
    channels: [deprecation]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!deprecation"]
        deprecation:
            type: stream
            channels: [deprecation]
            path: "%kernel.logs_dir%/deprecations.log"
